name = "大小盘动量轮动"
symbols = [ "159915.SZ", "510300.SH",]
start_date = "20100101"
end_date = "20250429"
benchmark = "510300.SH"
select = "SelectAll"
select_buy = [ "roc(close,20)>0.02",]
buy_at_least_count = 1
select_sell = [ "roc(close,20)<-0.02",]
sell_at_least_count = 1
order_by_signal = "roc(close,20)"
order_by_topK = 1
order_by_dropN = 0
order_by_DESC = true
weight = "WeighEqually"
period = "RunDaily"
[weight_fixed]
