name = "宽基动量轮动"
symbols = [ "159934.SZ", "513100.SH", "510300.SH", "159915.SZ",]
start_date = "20100101"
end_date = "20250503"
benchmark = "510300.SH"
select = "SelectAll"
select_buy = []
buy_at_least_count = 1
select_sell = []
sell_at_least_count = 1
order_by_signal = "roc(close,20)"
order_by_topK = 1
order_by_dropN = 0
order_by_DESC = true
weight = "WeighEqually"
period = "RunDaily"
period_days = 1

[weight_fixed]
